sonar.projectKey=org.jsoup:jsoup
sonar.host.url=http://localhost:9000
sonar.projectName=jsoup
sonar.projectVersion=1.23.1-SNAPSHOT
sonar.projectBaseDir=jsoup-fork
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java,src/main/java11
sonar.java.binaries=target/classes
